### ISSUE TITLE
Problems building for x86

### ISSUE THREAD

**Issue by beqabeqa473** [mush42/piper-rs#2]
Hi.

There are problems building ort1.15 on x86

**Comment by mush42** [comment]
Hi,

The issue has been reported, and a new version (1.15.1) which fixes the issue has been released.

Please fetch the latest changes from this repo.

Best
Musharraf

**Comment by beqabeqa473** [comment]
1.15.1 doesn't fix the problem

**Comment by mush42** [comment]
Yes it does. It works perfectly on my computer.

Please provide more information about the problem you're facing.: Rust version, the commit you're using to build `piper-rs`, and the error messages.

Best

**Comment by beqabeqa473** [comment]
problem was in rustc version beeing v1.69.
I've upgraded to v1.71 and problem has gone away.


thanks

On 7/19/23, Musharraf ***@***.***> wrote:
> Yes it does. It works perfectly on my computer.
>
> Please provide more information about the problem you're facing.: Rust
> version, the commit you're using to build `piper-rs`, and the error
> messages.
>
> Best
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/mush42/piper-rs/issues/2#issuecomment-1642637983
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
