### ISSUE TITLE
build failed on windows11

### ISSUE THREAD

**Issue by qt06** [mush42/piper-rs#3]
clone the latest verson from github. and on windows 11 and vs community 2022.
Run `cargo build` , I got the errors follow, I don't know how to do.:
The following warnings were emitted during compilation:
warning: could not execute `llvm-config` one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full path to valid `llvm-config` executable it will be used to try to find an instance of `libclang` on your system: "couldn't execute `llvm-config --prefix` (path=llvm-config) (error: program not found)"
error: failed to run custom build command for `clang-sys v1.6.1` Caused by:  process didn't exit successfully: `D:\git\sonata\target\debug\build\clang-sys-a94c0768b8712d9b\build-script-build` (exit code: 101)  --- stdout
  cargo:warning=could not execute `llvm-config` one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full path to valid `llvm-config` executable it will be used to try to find an instance of `libclang` on your system:  "couldn't execute `llvm-config --prefix` (path=llvm-config) (error: program not found)"  --- stderr  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\qt06\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clang-sys-1.6.1\build\dynamic.rs:206:45
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by mush42** [comment]
Probably you need to install llvm which includes clang and libclang
https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.1
